cmdb/urls.py
# coding=utf-8
#

from django.conf.urls import url

from host import *  # host, a10, 终端

from views import *  # es, user, oss

from dk import *

urlpatterns = [

    url(r'^host/add', host_add, name="host_add"),
    url(r'^host/del', host_del, name="host_del"),
    url(r'^host/alldel', host_alldel, name="host_alldel"),
    url(r'^host/(?P<id>\d+)/$', host_edit, name="host_edit"),
    # url(r'^group',  Group.as_view(), name="group"),
    url(r'^host_group', host_group_edit, name="host_group_edit"),
    url(r'^host', host, name="host"),
    # url(r'^(host)',  asset, name="host"),


    url(r'^clissh/(?P<hostid>\d+)', CliSSH.as_view(), name="clissh"),  # 生成临时账号密码供跳转xshell访问
    url(r'^webssh', WebSSH.as_view(), name="webssh"),
    url(r'^cmdrun', CmdRun.as_view(), name="cmdrun"),
    # url(r'^sshreplay/(?P<pk>\d+)/', SshReplay.as_view(), name='ssh_replay'),
    url(r'^sshlog', SshLogList.as_view(), name='sshlog'),
    url(r'^sshmonitor/(?P<channel>.*)', SshMonitor.as_view(), name='sshmonitor'),


    url(r'^es/(?P<pk>\d+)/indices/$', ESIndices.as_view(), name="es_indices"),
    url(r'^es/(?P<pk>\d+)/(?P<do>\w+)/(?P<index>\S+)/$', do_indices, name="do_indices"),
    url(r'^es/(?P<pk>\d+)/$', ESView.as_view(), name="es"),
    url(r'^es', ESList.as_view(), name="eslist"),


    url(r'^usergroup/(?P<pk>\d+)/$', UserGroupEdit.as_view(), name="usergroup_edit"),
    url(r'^user/(?P<pk>\d+)/$', UserEdit.as_view(), name="user_edit"),
    url(r'^user', UserList.as_view(), name="user"),


    url(r'^docker/info/(?P<pk>\d+)/', info, name="dockerinfo"),
    url(r'^docker/image/(?P<pk>\d+)/do/', image_do, name="docker_image_do"),
    url(r'^docker/image/(?P<pk>\d+)/rm/', image_rm, name="docker_image_rm"),
    url(r'^docker/image/(?P<pk>\d+)/', image, name="docker_image"),
    url(r'^docker/image/', image, name="docker_image"),

    url(r'^docker/container/(?P<pk>\d+)/do/', container_do, name="docker_container_do"),
    url(r'^docker/container/(?P<pk>\d+)/rm/', container_rm, name="docker_container_rm"),
    url(r'^docker/container/(?P<pk>\d+)/add/', container_add, name="docker_container_add"),
    url(r'^docker/container/(?P<pk>\d+)/', container, name="docker_container"),
    url(r'^docker/container/', container, name="docker_container"),

    url(r'^docker/net/(?P<pk>\d+)/do/', net_do, name="docker_net_do"),
    url(r'^docker/net/(?P<pk>\d+)/rm/', net_rm, name="docker_net_rm"),
    url(r'^docker/net/(?P<pk>\d+)/add/', net_add, name="docker_net_add"),
    url(r'^docker/net/(?P<pk>\d+)/', net, name="docker_net"),
    url(r'^docker/net/', net, name="docker_net"),

    url(r'^docker/host/', DockerHostList.as_view(), name="docker_host_list"),

    url(r'^docker/yml/(?P<pk>\d+)/$', DockerYmlEdit.as_view(), name="docker_yml_edit"),
    url(r'^docker/yml/add', DockerYmlAdd.as_view(), name="docker_yml_add"),
    url(r'^docker/yml/', DockerYmlList.as_view(), name="docker_yml_list"),
    url(r'^docker/compose/(?P<ids>.*)/del/', docker_compose_del, name="docker_compose_del"),
    url(r'^docker/compose/(?P<pk>\d+)/do/', DockerComposeDo.as_view(), name="docker_compose_do"),
    url(r'^docker/compose/(?P<pk>\d+)/$', DockerComposeEdit.as_view(), name="docker_compose_edit"),
    url(r'^docker/compose/add', DockerComposeAdd.as_view(), name="docker_compose_add"),
    url(r'^docker/compose/', DockerComposeList.as_view(), name="docker_compose_list"),


    url(r'^docker/imagefile/(?P<ids>.*)/del/', docker_imagefile_del, name="docker_imagefile_del"),
    url(r'^docker/imagefile/(?P<ids>.*)/load/(?P<hostid>\d+)', DockerImageFileLoad.as_view(), name="docker_imagefile_load"),
    url(r'^docker/imagefile/upload/$', DockerComposeUpload.as_view(), name="docker_imagefile_upload"),
    url(r'^docker/imagefile/$', DockerImageFileList.as_view(), name="docker_imagefile_list"),
    url(r'^docker/webssh', DockerWebSSH.as_view(), name="docker_webssh"),

]

dj/urls.py
# coding=utf-8
"""dj URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from views import index, login, logout, password_change, test
from django.conf import settings
from django.views.static import serve
# from django.contrib.auth.views import login,logout

from django.views.generic.base import RedirectView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/login', RedirectView.as_view(pattern_name="login"), ),  # 增加了otp验证
    url(r'^admin/password_change', RedirectView.as_view(pattern_name="password_change"), ),  # 增加了密码过期验证
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^login', login, name="login"),
    url(r'^password_change', password_change, name="password_change"),
    # url(r'^otp', otp, name="otp"),
    url(r'^logout', logout, name="logout"),
    url(r'^cmdb/', include('cmdb.urls', namespace="cmdb", app_name='cmdb')),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True), ),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^test$', test),
    url(r'^$', index),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }, name="media"),
]

import mimetypes
if '.svg' not in mimetypes.types_map:
    # CentOS7默认安装的python2.7.5版本偏旧，mime不含svg，导致svg图片不显示
    # 也可使用nginx，mime支持svg
    mimetypes.types_map['.svg'] = 'image/svg+xml'

cmdb/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, render_to_response, redirect, HttpResponse, get_object_or_404, Http404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView, ListView, View, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.cache import cache
import json
import threading
import time

from django.contrib.auth.models import User, Group

from cmdb.models import ES, Host
# from cmdb.models import Host, Balance
# from forms import HostForm, BalanceForm,

from elasticsearch import Elasticsearch
from conf import RedisTimeOut
from django.urls import reverse_lazy

import sys
reload(sys)
sys.setdefaultencoding('UTF-8')


class ESList(LoginRequiredMixin, ListView):
    template_name = "eslist.html"
    model = ES

    def get_context_data(self, **kwargs):
        kwargs['cmdb_es_active'] = 'active'
        return super(self.__class__, self).get_context_data(**kwargs)


class ESView(LoginRequiredMixin, UpdateView):
    template_name = "es.html"
    model = ES
    fields = ['cluster', 'node', 'host', 'port']

    def get_context_data(self, **kwargs):
        kwargs['cmdb_es_active'] = 'active'
        user = self.request.user
        if not self.object.host.chk_user_prem(user, 'other_do'):
            # 无主机操作权限时只读
            kwargs['readonly'] = 'readonly'
        return super(self.__class__, self).get_context_data(**kwargs)


class ESIndices(LoginRequiredMixin, DetailView):
    template_name = "esindices.html"
    model = ES
    indices_objs = []

    def get_indices(self, es, refresh=0, only_open=1):
        # 获取ES节点所有索引信息

        h = 'i,s,h,dc,ss'  # 指定所需获取的Elasticsearch API参数，_cat/indices?help
        # http://10.5.0.55:9201/_cat/indices?v&h=i,s,h,dc,dd,tm,ss
        hs = h.split(',')
        indices = cache.get('es_%d' % es.id)
        if refresh or not indices:
            url = 'http://%s:%s' % (es.host.ip, es.port)
            conn = Elasticsearch(hosts=[url], timeout=30)
            try:
                data = conn.cat.indices(params={'h': h})
                # print data,8989
            except Exception as e:
                print u'Error: connect failed', url, e
                self.indices_objs = str(e)
                return

            # 开始数据处理、格式化
            indices = []
            # print type(data),333
            if type(data) in (str, unicode):
                # Elasticsearch 5.*
                datas = data.splitlines()
                for i in datas:
                    line = i.split(' ')
                    index_datas = [l for l in line if l] + [''] * len(hs)
                    # index_key = index_datas[0]
                    # index_val = index_datas[1:]
                    indices.append(index_datas)

            else:
                # Elasticsearch 2.* 为字典列表
                datas = data
                for i in datas:
                    index_datas = [i[z] if i[z] else '' for z in hs]
                    indices.append(index_datas)

            # indices.sort(key=lambda x: (x[1], x[0]), reverse=True)  # 按第二列(打开/关闭)、第一列(索引名) 进行倒序排序
            # indices.sort(key=lambda x:x[0], reverse=True ) #按索引名进行倒序排序
            cache.set('es_%d' % es.id, indices, timeout=RedisTimeOut)
            # print indices

        class Obj:
            pass
        indices_objs = []
        for index in indices:
            # print index, 444
            if only_open and index[1] != 'open':
                # 显示开启项
                continue

            index_obj = Obj()
            n = 0
            for item in hs:
                setattr(index_obj, item, index[n])
                n += 1

            indices_objs.append(index_obj)

        self.indices_objs = indices_objs if indices_objs else '{"msg": "无符合条件的索引"}'

    # cache.iter_keys("*")

    def get_context_data(self, **kwargs):
        # import ipdb;ipdb.set_trace()
        try:
            refresh = int(self.request.GET.get('refresh', '0'))  # 是否使用缓存
            only_open = int(self.request.GET.get('o', '1'))  # 只显示开启的索引
        except:
            refresh = 0
            only_open = 1
        # indices = self.get_indices(self.object, refresh)
        th = threading.Thread(target=self.get_indices, args=(self.object, refresh, only_open))
        th.setDaemon(True)
        th.start()
        # print indices,777
        n = 0
        while not self.indices_objs:
            if n > 100:
                break
            time.sleep(1)
            # print n, '...'
            n += 1
        kwargs['indices'] = self.indices_objs if self.indices_objs else 'Error: TimeOut!'

        user = self.request.user
        if not self.object.host.chk_user_prem(user, 'other_do'):
            # 无主机操作权限时只读
            kwargs['readonly'] = 'readonly'
        return super(self.__class__, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        indices = context.get('indices')
        if type(indices) != list:
            # 从ES节点获取索引信息失败
            # print indices, 1111
            # print type(indices), 2222
            # import ipdb;ipdb.set_trace()
            return HttpResponse(indices)

        return self.render_to_response(context)


@login_required(login_url="/login")
def do_indices(request, pk, do, index):
    # ES索引 打开/关闭

    # print  pk, index, do, 9999
    # if request.method not in ('POST', 'PUT') :
    #     return HttpResponse('??')

    es = get_object_or_404(ES, id=pk)
    if do not in ('open', 'close'):
        if not (request.user.is_superuser and es.host.ip in ['10.2.21.21', '10.7.21.10', '10.5.0.55']):
            ret = {'status': '?', 'msg': '%s, 想要干什么??!!' % do, }
            return HttpResponse(json.dumps(ret))

    if not es.host.chk_user_prem(request.user, 'other_do'):
        msg = u'当前登陆用户没有ES主机other_do_host操作权限'
        return HttpResponse(json.dumps({'status': '?', 'msg': msg, }))

    ES_URL = 'http://%s:%s' % (es.host.ip, es.port)
    # print ES_URL
    conn = Elasticsearch(hosts=[ES_URL], timeout=30)

    try:
        msg = getattr(conn.indices, do)(index)
        try:
            result = int(msg['acknowledged'])
        except:
            result = '?'
        # import ipdb;ipdb.set_trace()
    except Exception as e:
        result = '0'
        msg = e

    # import ipdb;ipdb.set_trace()
    ret = {'status': str(result), 'msg': str(msg), }
    return HttpResponse(json.dumps(ret))


class UserList(LoginRequiredMixin, ListView):
    template_name = 'userlist.html'
    model = User
    # context_object_name = 'user_list'

    def get_context_data(self, **kwargs):
        kwargs['cmdb_user_active'] = 'active'
        kwargs['group_list'] = Group.objects.all().order_by('name')

        return super(self.__class__, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        if not self.request.user.has_perm('auth.view_user'):
            raise PermissionDenied
        return super(self.__class__, self).get(request, *args, **kwargs)


class UserEdit(LoginRequiredMixin, UpdateView):
    template_name = "user.html"
    model = User
    fields = ['username', 'email', 'is_superuser', 'is_staff']
    success_url = reverse_lazy('cmdb:user')
    perm_model = 'auth.change_user'

    def get(self, request, *args, **kwargs):
        if not self.request.user.has_perm(self.perm_model):
            raise PermissionDenied
        return UpdateView.get(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # print self.object, 898989
        kwargs['hosts_on'] = self.object.host_set.all()
        kwargs['hosts_off'] = set(Host.objects.all()) - set(kwargs['hosts_on'])  # 差集
        # kwargs['apps_on'] = self.object.app_set.all()
        # kwargs['apps_off'] = set(App.objects.all()) - set(kwargs['apps_on'])  # 差集
        return UpdateView.get_context_data(self, **kwargs)

    def post(self, request, *args, **kwargs):

        # print args, kwargs, 8888888, request.POST
        host_ids = request.POST.getlist('host', [])
        app_ids = request.POST.getlist('app', [])
        self.object = self.get_object()
        form = self.get_form()
        # import ipdb;ipdb.set_trace()
        if form.is_valid():
            return self.form_valid(form, host_ids, app_ids)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, host_ids=[], app_ids=[]):
        self.object = form.save()

        # 添加m2m关联
        hosts_new = Host.objects.filter(id__in=host_ids)
        try:
            self.object.host_set.set(hosts_new)
        except:
            print 'Error: host：%s, 出现未知异常情况，有主机刚被删除？！' % host_ids

        apps_new = App.objects.filter(id__in=app_ids)
        try:
            self.object.app_set.set(apps_new)
        except:
            print 'Error: host：%s, 出现未知异常情况，有APP刚被删除？！' % app_ids

        return redirect(self.get_success_url())
        # return super(self.__class__, self).form_valid(form)


class UserGroupEdit(UserEdit):
    template_name = "usergroup.html"
    model = Group
    fields = ['name', ]
    perm_model = 'auth.change_group'

# from django.http import HttpRequest

cmdb/templates/eslist.html
{% extends "_base.html" %}


{% block  title %}资产信息{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>资产管理</a>
                </li>
                <li class="active">
                    <strong>ES节点列表</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>资产信息</h5>

                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">

                            <a href="/admin/cmdb/es/add/" class="btn btn-primary" target="_blank">
                                增加ES节点</a>
<!-- 
                            <a class="btn btn-danger" data-toggle="modal"
                               data-target="#myModal2">批量删除
                            </a>
 -->




                            <form class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <!-- <th width="20"><input type="checkbox" id="CheckedAll"></th> -->
                                        <th>标识名称</th>
                                        <th>所在主机</th>
                                        <th>端口</th>
                                        <th>集群名</th>
                                        <th>节点名</th>
                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   object_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <!-- <td><input type="checkbox" value="{{ row.id }}"  name="id"></td> -->
                                            <td class="center"><a
                                                    href="{% url 'cmdb:eslist' %}/{{ row.id }}/">{{ row.name }}</a>
                                            </td>
                                            <td class="center">{{ row.host }}</td>
                                            <td class="center">{{ row.port }}</td>
                                            <td class="center">{{ row.cluster }}</td>
                                            <td class="center">{{ row.node }}</td>

                                            <td>
                                                <a class="btn btn-xs btn-success " href="{% url 'cmdb:eslist' %}/{{ row.id }}/" target="_blank">索引管理</a>
                                                <a class="btn btn-primary  btn-xs " href="/admin/cmdb/es/{{ row.id }}/" target="_blank">修改信息</a>
                                                <!-- <a class="btn btn-danger  btn-xs  asset_del_id"     data-toggle="modal" data-target="#myModal1">删除 </a> -->

                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}



cmdb/templates/hostlist_2.html
{% extends "_base.html" %}


{% block  title %}资产信息{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                {% if parent_name %}
                <li class="active">
                    <strong>({{ parent_name }}) 下属主机列表</strong>
                </li>
                <li>
                    <a href='javascript:history.go(-1)'>返回上一层</a>
                </li>
                {% else %}
                <li>
                    虚拟机管理
                </li>
                <li class="active">
                    <strong>虚拟机列表</strong>
                </li>
                {% endif %}
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>资产信息</h5>

                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">
                            {% if not parent_name %}
                            <a href="{% url 'cmdb:host_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <a class="btn btn-danger" data-toggle="modal"
                               data-target="#myModal2">批量删除
                            </a>
                            <a class="btn btn-info" onclick="javascript:run_cmd3()">批量更新配置
                            </a>
                            <form id="cmd3" action="{% url 'cmdb:cmdrun' %}" method="post" target="_blank">{% csrf_token %}<input type="hidden" name="hosts"/><input type="hidden" name="cmd"/></form>
                            {% endif %}




                            <form id="form_asset_all" class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th width="120">名称</th>
                                        <th>主机名</th>
                                        <th>管理IP</th>
                                        <th>tomcat版本</th>
                                        <th>JDK版本</th>
                                        <th>系统版本</th>
                                        <th>配置更新</th>
                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   hosts %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}"  name="id"></td>
                                            <td class="center"><a
                                                    href="{% url 'cmdb:host' %}/{{ row.id }}/">{{ row.name }}</a>
                                            </td>
                                            <td>{{ row.hostname }}</td>
                                            <td>{{ row.ip }}</td>
                                            <td>{{ row.tomcat_ver }}</td>
                                            <td>{{ row.jdk_ver }}</td>
                                            <td>{{ row.os }}</td>
                                            <td>{{ row.agenttime }}</td>
                                            <td>
                                                <a class="btn btn-primary  btn-xs " href="/admin/cmdb/host/{{ row.id }}/change/" target="_blank">详情</a>
                                                <a class="btn btn-xs btn-success " title="Xshell终端" onclick="javascript:xshell(this)">终端</a>
                                                <a class="btn btn-xs btn-info " href="{% url  'cmdb:webssh' %}#webssh_{{ row.id }}" title="网页终端" target="_blank">终端</a>
                                                <a class="btn btn-xs btn-warning" href="{% url  'cmdb:webssh' %}#sftp_{{ row.id }}" title="SFTP" target="_blank">文件</a>
                                                {% if not parent_name %}
                                                <a class="btn btn-xs btn-info" title="更新主机配置" onclick="javascript:run_cmd3(this)">更新</a>
                                                <a class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal1" onclick="javascript:del_host(this)">删除 </a>
                                                {% endif %}


                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal inmodal" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">删除</h4>
                    <span id="error" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="asset_del_form">
                    <div class="modal-body">

                        <div class="form-group"><input type="text" name="nid" style="display:none"/></div>
                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm asset_del">删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="modal inmodal" id="myModal2" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">批量删除</h4>
                    <span id="error_all" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="del_form">
                    <div class="modal-body">

                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm  asset_all_del"> 批量删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

{% block footer-js %}


        <script>

            function xshell(obj){
                var hostid = $(obj).parent().parent().attr('id');
                var url="/cmdb/clissh/"+hostid;
                // console.log(url);

                // var frame = document.getElementById('clissh_frame')

                $.ajax({
                    url: url,
                    type: 'GET',
                    timeout: 3000,
                    async: false,
                    // async: true,
                    error: function(){
                        alert("创建xshell终端超时！请联系CMDB管理员");
                    },
                    success: function(ssh_url){
                        // console.log(ssh_url);
                        window.location.href=ssh_url;
                        // console.log(frame.src)
                    }
                });

            }


            function run_cmd3(obj=null){
                // 执行自定义命令，更新客户端机器配置信息
                if (obj) {
                    // 更新单台主机配置
                    var host_ids = $(obj).parent().parent().attr('id');
                }
                else {
                    var host_ids = '';
                    var cs=document.getElementsByName('id');
                    for (i=0; i < cs.length; i++) {
                        if (cs[i].checked) {
                            host_ids = host_ids+cs[i].value+',';
                            // console.log(cs[i].value);
                        }
                    }
                }

                var cmd3_form = $("#cmd3")[0];
                cmd3_form.hosts.value = host_ids;
                var url = window.location.protocol + "//" + window.location.host;
                cmd3_form.cmd.value = "wget -t1 -T5 -O agent.py "+url+"/static/agent.py >& /dev/null && python agent.py 0 "+url;

                // 提交自定义命令
                cmd3_form.submit();

            }
            function del_host(obj){
                var id = $(obj).parent().parent().attr('id');
                $('#asset_del_form').find('input[name="nid"]').val(id);
            }
            $(function () {

                $('.asset_del').click(function () {
                    $.ajax({
                        url: "/cmdb/host/del",
                        type: 'POST',
                        data: $('#asset_del_form').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error').text(obj.error);
                            }
                        }
                    })
                });

                $('.asset_all_del').click(function () {
                    var chk_value =[];
                    $('input[name="id"]:checked').each(function(){ 
                        chk_value.push($(this).val()); 
                    });
                    if (chk_value.length==0) {
                        // alert("未选择任何主机，操作已忽略");
                        // $('#error_all').text("未选择任何主机..");
                        return
                    }
                    $.ajax({
                        url: "/cmdb/host/alldel",
                        type: 'POST',
                        data: $('#form_asset_all').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error_all').text(obj.error);
                            }
                        }

                    })
                });


            });


        </script>

{% endblock %}

cmdb/templates/sshreplay.html


  <asciinema-player src="{{logfile}}"></asciinema-player>
