cmdb/urls.py
# coding=utf-8
#

from django.conf.urls import url

from host import *  # host, a10, 终端

from views import *  # es, user, oss

from dk import *

urlpatterns = [

    url(r'^host/add', host_add, name="host_add"),
    url(r'^host/del', host_del, name="host_del"),
    url(r'^host/alldel', host_alldel, name="host_alldel"),
    url(r'^host/(?P<id>\d+)/$', host_edit, name="host_edit"),
    # url(r'^group',  Group.as_view(), name="group"),
    url(r'^host_group', host_group_edit, name="host_group_edit"),
    url(r'^host', host, name="host"),
    # url(r'^(host)',  asset, name="host"),


    url(r'^clissh/(?P<hostid>\d+)', CliSSH.as_view(), name="clissh"),  # 生成临时账号密码供跳转xshell访问
    url(r'^webssh', WebSSH.as_view(), name="webssh"),
    url(r'^cmdrun', CmdRun.as_view(), name="cmdrun"),
    # url(r'^sshreplay/(?P<pk>\d+)/', SshReplay.as_view(), name='ssh_replay'),
    url(r'^sshlog', SshLogList.as_view(), name='sshlog'),
    url(r'^sshmonitor/(?P<channel>.*)', SshMonitor.as_view(), name='sshmonitor'),


    url(r'^es/(?P<pk>\d+)/indices/$', ESIndices.as_view(), name="es_indices"),
    url(r'^es/(?P<pk>\d+)/(?P<do>\w+)/(?P<index>\S+)/$', do_indices, name="do_indices"),
    url(r'^es/(?P<pk>\d+)/$', ESView.as_view(), name="es"),
    url(r'^es', ESList.as_view(), name="eslist"),


    url(r'^usergroup/(?P<pk>\d+)/$', UserGroupEdit.as_view(), name="usergroup_edit"),
    url(r'^user/(?P<pk>\d+)/$', UserEdit.as_view(), name="user_edit"),
    url(r'^user', UserList.as_view(), name="user"),


    url(r'^docker/info/(?P<pk>\d+)/', info, name="dockerinfo"),
    url(r'^docker/image/(?P<pk>\d+)/do/', image_do, name="docker_image_do"),
    url(r'^docker/image/(?P<pk>\d+)/rm/', image_rm, name="docker_image_rm"),
    url(r'^docker/image/(?P<pk>\d+)/', image, name="docker_image"),
    url(r'^docker/image/', image, name="docker_image"),

    url(r'^docker/container/(?P<pk>\d+)/do/', container_do, name="docker_container_do"),
    url(r'^docker/container/(?P<pk>\d+)/rm/', container_rm, name="docker_container_rm"),
    url(r'^docker/container/(?P<pk>\d+)/add/', container_add, name="docker_container_add"),
    url(r'^docker/container/(?P<pk>\d+)/', container, name="docker_container"),
    url(r'^docker/container/', container, name="docker_container"),

    url(r'^docker/net/(?P<pk>\d+)/do/', net_do, name="docker_net_do"),
    url(r'^docker/net/(?P<pk>\d+)/rm/', net_rm, name="docker_net_rm"),
    url(r'^docker/net/(?P<pk>\d+)/add/', net_add, name="docker_net_add"),
    url(r'^docker/net/(?P<pk>\d+)/', net, name="docker_net"),
    url(r'^docker/net/', net, name="docker_net"),

    url(r'^docker/host/', DockerHostList.as_view(), name="docker_host_list"),

    url(r'^docker/yml/(?P<pk>\d+)/$', DockerYmlEdit.as_view(), name="docker_yml_edit"),
    url(r'^docker/yml/add', DockerYmlAdd.as_view(), name="docker_yml_add"),
    url(r'^docker/yml/', DockerYmlList.as_view(), name="docker_yml_list"),
    url(r'^docker/compose/(?P<ids>.*)/del/', docker_compose_del, name="docker_compose_del"),
    url(r'^docker/compose/(?P<pk>\d+)/do/', DockerComposeDo.as_view(), name="docker_compose_do"),
    url(r'^docker/compose/(?P<pk>\d+)/$', DockerComposeEdit.as_view(), name="docker_compose_edit"),
    url(r'^docker/compose/add', DockerComposeAdd.as_view(), name="docker_compose_add"),
    url(r'^docker/compose/', DockerComposeList.as_view(), name="docker_compose_list"),


    url(r'^docker/imagefile/(?P<ids>.*)/del/', docker_imagefile_del, name="docker_imagefile_del"),
    url(r'^docker/imagefile/(?P<ids>.*)/load/(?P<hostid>\d+)', DockerImageFileLoad.as_view(), name="docker_imagefile_load"),
    url(r'^docker/imagefile/upload/$', DockerComposeUpload.as_view(), name="docker_imagefile_upload"),
    url(r'^docker/imagefile/$', DockerImageFileList.as_view(), name="docker_imagefile_list"),
    url(r'^docker/webssh', DockerWebSSH.as_view(), name="docker_webssh"),

]

dj/urls.py
# coding=utf-8
"""dj URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from views import index, login, logout, password_change, test
from django.conf import settings
from django.views.static import serve
# from django.contrib.auth.views import login,logout

from django.views.generic.base import RedirectView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/login', RedirectView.as_view(pattern_name="login"), ),  # 增加了otp验证
    url(r'^admin/password_change', RedirectView.as_view(pattern_name="password_change"), ),  # 增加了密码过期验证
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^login', login, name="login"),
    url(r'^password_change', password_change, name="password_change"),
    # url(r'^otp', otp, name="otp"),
    url(r'^logout', logout, name="logout"),
    url(r'^cmdb/', include('cmdb.urls', namespace="cmdb", app_name='cmdb')),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True), ),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^test$', test),
    url(r'^$', index),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }, name="media"),
]

import mimetypes
if '.svg' not in mimetypes.types_map:
    # CentOS7默认安装的python2.7.5版本偏旧，mime不含svg，导致svg图片不显示
    # 也可使用nginx，mime支持svg
    mimetypes.types_map['.svg'] = 'image/svg+xml'

templates/_base.html

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% block header %}
    {% endblock %}

</head>

<!-- <body class="boxed-layout pace-done"> -->
<body class="pace-done">

<div id="wrapper">
    {% block left %}
        {% include "_left.html" %}
        {#% include "_left.html" with cmdb_host_active="active" %#}
    {% endblock left %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>


{% include  "_js.html" %}

{% block footer-js %}
{% endblock %}





</body>

</html>

templates/_css.html
{% load  static %}

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

<link href="{% static 'css/animate.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css'  %} " rel="stylesheet">

<link href="{% static 'css/datatables.min.css' %} "   rel="stylesheet">

<link href="{% static 'css/plugins/select2/select2.min.css' %} "   rel="stylesheet">

templates/_footer.html
<div class="footer">

    <div class="pull-right">
        <strong>Copyright</strong> cmdb &copy; 2017-2018
    </div>
</div>

templates/_js.html
{% load  static %}

<script src="{% static  'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static  'js/bootstrap.min.js' %}"></script>
<script src="{% static  'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static  'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  'js/inspinia.js' %} "></script>
<script src="{% static  'js/plugins/pace/pace.min.js' %}"></script>


<script src="{% static  'js/datatables.min.js' %}"></script>


<script src="{% static  'js/plugins/select2/select2.full.min.js' %}"></script>



<script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>




<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {
        $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            order: [[0, 'asc']],
            columnDefs: [{
                'targets': [0],    //不排序
                'orderable': false,
                'orderData': [ 0, 1 ] //第1列排再按第二列排
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [
                    {extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ],
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "全部"]]
        });


    });


       $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });





    </script>

templates/_left.html
{% load tags %}
{%  menu_prem as menu %}

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                <span><img alt="image" class="img-circle" src="/static/img/profile_small.jpg"></span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs"> <strong class="font-bold">{{ user }}</strong>

                        </span>
                        <span class="text-muted text-xs block">
                            {% if user.is_superuser %}
                            管理员 {% elif user.is_authenticated %}普通用户{% else %}访客{% endif %}
                            <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        {% if user.is_authenticated %}
                        <li><a href="/password_change/" target="_blank">修改密码</a></li>
                        <li><a href="{% url 'logout' %}">登出</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">登入</a></li>
                        {% endif %}
                    </ul>

                </div>
                <div class="logo-element">
                    CMDB
                </div>
            </li>
            <li>
                <a href="/"><i class="fa fa-cubes"></i> <span class="nav-label">首页</span>
                   </a>

            </li>
            {% if menu.view_host or menu.view_balance or menu.view_app or menu.deploy_host or menu.view_user or menu.view_group or menu.other_do_host %}
            <li class="{% firstof cmdb_host_active cmdb_host_2_active cmdb_host_1_active cmdb_host_4_active cmdb_balance_active cmdb_other_active cmdb_app_active cmdb_conf_active cmdb_group_active cmdb_es_active cmdb_user_active cmdb_appsh_active cmdb_appconfile_active cmdb_cert_active cmdb_oss_file %}">
                <a><i class="fa fa-server"></i> <span class="nav-label">资产管理</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    {% if menu.view_host %}
                    <li  class="{{ cmdb_host_2_active }}"><a href="{% url 'cmdb:host' %}/?t=2">虚拟机</a></li>
                    {# <li  class="{{ cmdb_host_1_active }}"><a href="{% url 'cmdb:host' %}/?t=1">物理机</a></li> #}
                    {# <li  class="{{ cmdb_host_4_active }}"><a href="{% url 'cmdb:host' %}/?t=4">交换机</a></li> #}
                    {% endif %}

                    {% if menu.view_user or menu.view_group %}
                    <li  class="{{ cmdb_user_active }}"><a href="{% url 'cmdb:user' %}">用户权限</a></li>
                    {% endif %}
                    {% if menu.other_do_host %}
                    <li  class="{{ cmdb_es_active }}"><a href="{% url 'cmdb:eslist' %}">ES 节点</a></li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}

            {% if menu.ssh_host or menu.grep_host or menu.run_sh_host or menu.run_cmd_host %}
            <li class="{% firstof cmdb_webssh_active cmdb_cmdrun_active cmdb_cmdrun2_active cmdb_appsh_run_active cmdb_sshlog_active %}">
                <a><i class="fa fa-calendar"></i> <span class="nav-label">终端命令</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    {% if menu.ssh_host %}
                    <li  class="{{ cmdb_webssh_active }}"><a href="{% url 'cmdb:webssh' %}">终端登陆</a></li>
                    {% endif %}
                    {% if menu.webssh_log %}
                    <li  class="{{ cmdb_sshlog_active }}"><a href="{% url 'cmdb:sshlog' %}">终端日志</a></li>
                    {% endif %}
                    {% if menu.grep_host or menu.run_sh_host or menu.run_cmd_host %}
                    <li  class="{{ cmdb_cmdrun_active }}"><a href="{% url 'cmdb:cmdrun' %}">服务器命令</a></li>
                    {# <li  class="{{ cmdb_cmdrun2_active }}"><a href="{% url 'cmdb:cmdrun' %}?s=2">交换机命令</a></li> #}
                    {% endif %}

                </ul>
            </li>
            {% endif %}


            {% if menu.view_docker %}
            <li class="{% firstof cmdb_docker_host_active cmdb_docker_image_active cmdb_docker_image_file_active cmdb_docker_container_active cmdb_docker_net_active cmdb_docker_yml_active cmdb_docker_compose_active %}">
                <a><i class="fa fa-calendar"></i> <span class="nav-label">Docker管理</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li  class="{{ cmdb_docker_host_active }}"><a href="{% url 'cmdb:docker_host_list' %}">宿主机</a></li>
                    <li  class="{{ cmdb_docker_yml_active }}"><a href="{% url 'cmdb:docker_yml_list' %}">YML管理</a></li>
                    {% if menu.view_dockercompose %}
                    <li  class="{{ cmdb_docker_compose_active }}"><a href="{% url 'cmdb:docker_compose_list' %}">容器编排</a></li>
                    {% endif %}

                    <li  class="{{ cmdb_docker_image_file_active }}"><a href="{% url 'cmdb:docker_imagefile_list' %}">镜像包</a></li>
                    {% if menu.images_manage %}
                    <li  class="{{ cmdb_docker_image_active }}"><a href="{% url 'cmdb:docker_image' %}">镜像管理</a></li>
                    {% endif %}
                    {% if menu.containers_manage %}
                    <li  class="{{ cmdb_docker_container_active }}"><a href="{% url 'cmdb:docker_container' %}">容器管理</a></li>
                    {% endif %}
                    {% if menu.net_manage %}
                    <li  class="{{ cmdb_docker_net_active }}"><a href="{% url 'cmdb:docker_net' %}">容器网络</a></li>
                    {% endif %}


                </ul>
            </li>
            {% endif %}


            {% if menu.view_admin %}
            <li class="landing_link">
                <a><i class="fa fa-database"></i> 
                    <span class="nav-label">后台管理</span>
                    <span  class="label label-warning pull-right">Django</span>
                </a>
                <ul class="nav nav-second-level">
                    <li><a href="/admin/" target="_blank">后台主页</a></li>

                    {% if menu.view_user %}
                    <li><a href="/admin/auth/user/" target="_blank">网站用户</a></li>
                    {% endif %}
                    {% if menu.view_sshuser %}
                    <li><a href="/admin/cmdb/sshuser/" target="_blank">SSH用户</a></li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}

        </ul>

    </div>
</nav>

templates/_top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
{#                    <form role="search" class="navbar-form-custom" method="post" action="#">#}
{#                        <div class="form-group">#}
{#                            <input type="text" placeholder="请输入搜索内容" class="form-control" name="top-search" id="top-search">#}
{#                        </div>#}
{#                    </form>#}
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    欢迎 {{ user  }} 使用 CMDB系统  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    {% if user.is_authenticated %}
                    <li><a href="/logout"><i class="fa fa-sign-out"></i> 注销</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> 登录</a></li>
                    {% endif %}
                </ul>

            </nav>
        </div>

templates/login.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>CMDB系统 | 登录</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <h3>欢迎登录CMDB系统</h3>
        <form class="m-t" role="form" action=""  method="POST">
            {% csrf_token %}
            {% block content %}
            <div class="form-group">
                <input type="text"  name="username" class="form-control" placeholder="用户名" required="">
            </div>
            <div class="form-group">
                <input type="password"  name="password" class="form-control" placeholder="密码" required="">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">登录</button>

            <span style="color: red;"> {{ error_msg }}</span><br>
            <!-- <a href="#"><small>忘记密码?</small></a> -->
            <!-- <a class="btn btn-sm btn-white btn-block" href="#">创建一个帐户</a> -->
            {% endblock %}
        </form>
        <p class="m-t"> <small>Copyright</strong> CMDB系统 &copy; 2017</small> </p>

    </div>

    <!-- Mainly scripts -->
    <script src="/static/js/jquery-3.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

</body>

</html>

templates/otp.html
{% extends "login.html" %}

            {% block content %}
            <p>用户({{ user }}) OTP验证</p>
            {% if show_otp %}
            <img src="data:image/png;base64,{{ base64_data }}"><br/>
            <p>首次登陆？<br/>请使用手机otp工具(比如freeotp等)<br/>扫描二维码，
            若是Google Authentication则可输入“<span style="color: red;">{{ secret.0 }}</span>”，
            将获取的t-otp验证码输入下框中验证</p>
            {% endif %}
            <div class="form-group">
                <input type="text"  name="totp" class="form-control" placeholder="T-otp验证" required>
            </div>
            <div class="form-inline">
                <button type="submit" class="btn btn-primary">验证</button>
                <a class="btn btn-info btn-outline col-sm-offset-1" href="/logout">取消</a>
            </div>
            <span> 注意：otp验证客户端，比如手机时间必需和网站服务器时间一致，每间隔30秒刷新一次</span><br>
            <span style="color: red;"> {{ error_msg|safe }}</span><br>
            {% endblock %}

templates/password.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>CMDB系统 | 修改密码</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        {% if not ok_msg %}
        <h3>修改 {{ user }} 用户密码</h3>
        <form class="m-t" role="form" action=""  method="POST">
            {% csrf_token %}
            {% block content %}
            <div class="form-group">
                <input type="password"  name="password" class="form-control" placeholder="旧密码" required="">
            </div>
            <div class="form-group">
                <input type="password"  name="password2" class="form-control" placeholder="新密码" required="">
            </div>
            <div class="form-group">
                <input type="password"  name="password3" class="form-control" placeholder="确认密码" required="">
            </div>
            <div class="form-inline">
                <button type="submit" class="btn btn-primary">确定</button>
                <a class="btn btn-info btn-outline col-sm-offset-1" href="javascript:location='/';">取消</a>
            </div>

            <span style="color: red;"> {{ error_msg }}</span><br>
            {% endblock %}
        </form>
        <p class="m-t"> <small>Copyright</strong> CMDB系统 &copy; 2017</small> </p>

        {% else %}
        <div class="text-success"><h2>{{ ok_msg }}</h2></div>
        <script type="text/javascript">
            setTimeout(function(){
                location = "/login";
            }, 3000);
        </script>
        {% endif %}
    </div>

    <!-- Mainly scripts -->
    <script src="/static/js/jquery-3.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>




</body>

</html>