cmdb/urls.py
# coding=utf-8
#

from django.conf.urls import url

from host import *  # host, a10, 终端

from views import *  # es, user, oss

from dk import *

urlpatterns = [

    url(r'^host/add', host_add, name="host_add"),
    url(r'^host/del', host_del, name="host_del"),
    url(r'^host/alldel', host_alldel, name="host_alldel"),
    url(r'^host/(?P<id>\d+)/$', host_edit, name="host_edit"),
    # url(r'^group',  Group.as_view(), name="group"),
    url(r'^host_group', host_group_edit, name="host_group_edit"),
    url(r'^host', host, name="host"),
    # url(r'^(host)',  asset, name="host"),


    url(r'^clissh/(?P<hostid>\d+)', CliSSH.as_view(), name="clissh"),  # 生成临时账号密码供跳转xshell访问
    url(r'^webssh', WebSSH.as_view(), name="webssh"),
    url(r'^cmdrun', CmdRun.as_view(), name="cmdrun"),
    # url(r'^sshreplay/(?P<pk>\d+)/', SshReplay.as_view(), name='ssh_replay'),
    url(r'^sshlog', SshLogList.as_view(), name='sshlog'),
    url(r'^sshmonitor/(?P<channel>.*)', SshMonitor.as_view(), name='sshmonitor'),


    url(r'^es/(?P<pk>\d+)/indices/$', ESIndices.as_view(), name="es_indices"),
    url(r'^es/(?P<pk>\d+)/(?P<do>\w+)/(?P<index>\S+)/$', do_indices, name="do_indices"),
    url(r'^es/(?P<pk>\d+)/$', ESView.as_view(), name="es"),
    url(r'^es', ESList.as_view(), name="eslist"),


    url(r'^usergroup/(?P<pk>\d+)/$', UserGroupEdit.as_view(), name="usergroup_edit"),
    url(r'^user/(?P<pk>\d+)/$', UserEdit.as_view(), name="user_edit"),
    url(r'^user', UserList.as_view(), name="user"),


    url(r'^docker/info/(?P<pk>\d+)/', info, name="dockerinfo"),
    url(r'^docker/image/(?P<pk>\d+)/do/', image_do, name="docker_image_do"),
    url(r'^docker/image/(?P<pk>\d+)/rm/', image_rm, name="docker_image_rm"),
    url(r'^docker/image/(?P<pk>\d+)/', image, name="docker_image"),
    url(r'^docker/image/', image, name="docker_image"),

    url(r'^docker/container/(?P<pk>\d+)/do/', container_do, name="docker_container_do"),
    url(r'^docker/container/(?P<pk>\d+)/rm/', container_rm, name="docker_container_rm"),
    url(r'^docker/container/(?P<pk>\d+)/add/', container_add, name="docker_container_add"),
    url(r'^docker/container/(?P<pk>\d+)/', container, name="docker_container"),
    url(r'^docker/container/', container, name="docker_container"),

    url(r'^docker/net/(?P<pk>\d+)/do/', net_do, name="docker_net_do"),
    url(r'^docker/net/(?P<pk>\d+)/rm/', net_rm, name="docker_net_rm"),
    url(r'^docker/net/(?P<pk>\d+)/add/', net_add, name="docker_net_add"),
    url(r'^docker/net/(?P<pk>\d+)/', net, name="docker_net"),
    url(r'^docker/net/', net, name="docker_net"),

    url(r'^docker/host/', DockerHostList.as_view(), name="docker_host_list"),

    url(r'^docker/yml/(?P<pk>\d+)/$', DockerYmlEdit.as_view(), name="docker_yml_edit"),
    url(r'^docker/yml/add', DockerYmlAdd.as_view(), name="docker_yml_add"),
    url(r'^docker/yml/', DockerYmlList.as_view(), name="docker_yml_list"),
    url(r'^docker/compose/(?P<ids>.*)/del/', docker_compose_del, name="docker_compose_del"),
    url(r'^docker/compose/(?P<pk>\d+)/do/', DockerComposeDo.as_view(), name="docker_compose_do"),
    url(r'^docker/compose/(?P<pk>\d+)/$', DockerComposeEdit.as_view(), name="docker_compose_edit"),
    url(r'^docker/compose/add', DockerComposeAdd.as_view(), name="docker_compose_add"),
    url(r'^docker/compose/', DockerComposeList.as_view(), name="docker_compose_list"),


    url(r'^docker/imagefile/(?P<ids>.*)/del/', docker_imagefile_del, name="docker_imagefile_del"),
    url(r'^docker/imagefile/(?P<ids>.*)/load/(?P<hostid>\d+)', DockerImageFileLoad.as_view(), name="docker_imagefile_load"),
    url(r'^docker/imagefile/upload/$', DockerComposeUpload.as_view(), name="docker_imagefile_upload"),
    url(r'^docker/imagefile/$', DockerImageFileList.as_view(), name="docker_imagefile_list"),
    url(r'^docker/webssh', DockerWebSSH.as_view(), name="docker_webssh"),

]

dj/urls.py
# coding=utf-8
"""dj URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from views import index, login, logout, password_change, test
from django.conf import settings
from django.views.static import serve
# from django.contrib.auth.views import login,logout

from django.views.generic.base import RedirectView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/login', RedirectView.as_view(pattern_name="login"), ),  # 增加了otp验证
    url(r'^admin/password_change', RedirectView.as_view(pattern_name="password_change"), ),  # 增加了密码过期验证
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^login', login, name="login"),
    url(r'^password_change', password_change, name="password_change"),
    # url(r'^otp', otp, name="otp"),
    url(r'^logout', logout, name="logout"),
    url(r'^cmdb/', include('cmdb.urls', namespace="cmdb", app_name='cmdb')),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True), ),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^test$', test),
    url(r'^$', index),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }, name="media"),
]

import mimetypes
if '.svg' not in mimetypes.types_map:
    # CentOS7默认安装的python2.7.5版本偏旧，mime不含svg，导致svg图片不显示
    # 也可使用nginx，mime支持svg
    mimetypes.types_map['.svg'] = 'image/svg+xml'

cmdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# from django.utils.timezone import now, localdate
from datetime import datetime, timedelta

from django.core.cache import cache
from django import template
from django.contrib.auth.models import User, Group
import traceback
import paramiko
import docker
import os
import sys
import cStringIO
import urlparse
import uuid
from .conf import YmlDir, ImgDir, DOCKER_CERT_PATH
from compose.cli.main import dispatch as docker_compose
import tarfile
import json
from .opt import get_AES

# from conf import YmlDir

# from django.db.models.options import Options
# old_contribute_to_class = Options.contribute_to_class


# def new_contribute_to_class(instance, cls, name):
#     # 设置verbose_name_plural为verbose_name
#     old_contribute_to_class(instance, cls, name)
#     instance.verbose_name_plural = instance.verbose_name
# models.options.Options.contribute_to_class = new_contribute_to_class


class HostGroup(models.Model):
    name = models.CharField(u"组名/区域", max_length=30, unique=True)
    ip = models.CharField(u"IP匹配", help_text='IP开头字符，比如Core组IP为10.2.4.开头。用于客户端脚本添加新主机时自动设置组，不支持通配符', max_length=20, default='', blank=True)
    desc = models.CharField(u"描述", max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = '主机分组'

    def __unicode__(self):
        return self.name

    @staticmethod
    def get_group(ip):
        # 客户端脚本自动添加主机时，自动设置主机所属组(安全区域)

        groups = HostGroup.objects.exclude(ip='').order_by('-ip')
        group_id = 0
        for group in groups:
            if ip.startswith(group.ip):
                group_id = group.id
                break
        return group_id


class SshUser(models.Model):
    # 各服务器SSH登陆用户
    name = models.CharField(u"名称", max_length=50, default='', help_text='标识名称，当不同服务器使用相同的SSH账号名，但密码不同时，此项名称可进行区分。')
    username = models.CharField(u"SSH账号", max_length=50, default='', )
    password = models.CharField(u"密码", max_length=50, default='', null=True, blank=True, help_text='若不想修改原密码，不用设置此项')
    changetime = models.DateTimeField('最后修改', auto_now=True, blank=True, null=True)
    text = models.TextField(u"备注信息", default='', null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = '主机SSH用户'
        unique_together = [('name', 'username'), ]

    def __unicode__(self):
        return '%s - %s' % (self.name, self.username)

    def save(self, *args, **kwargs):

        if self.password:
            password_aes = get_AES(password=self.password, encode=1)  # AES加密
            self.password = password_aes
        elif self.id:
            del self.password  # 防止不修改密码时，提交的空密码覆盖原有数据
        # import ipdb;ipdb.set_trace()
        super(self.__class__, self).save(*args, **kwargs)  # Call the "real" save() method.


class Host(models.Model):
    # 虚拟机、物理机 等设备
    ASSET_STATUS = (
        (1, u"在用"),
        (2, u"备用"),
        (3, u"故障"),
        (4, u"下线"),
        (6, u"其它"),
    )

    ASSET_TYPE = (
        (1, u"物理机"),
        (2, u"虚拟机"),
        (3, u"容器"),
        (4, u"H3C交换机"),
        (6, u"其它")
    )

    name = models.CharField(max_length=100, verbose_name=u"标识名称", default='', help_text='用于人工辨别，自动脚本默认设置为主机名，可改为其它便于人员识别的名称')
    hostname = models.CharField(max_length=50, verbose_name=u"主机名/计算机名", unique=True, help_text='关键字段，请谨慎修改')  # 服务器数据以计算机名为锚，以验证身份不重复添加数据
    ip = models.GenericIPAddressField(u"管理IP", max_length=15, help_text='若有多个IP且主机名无指定解析则默认为0.0.0.0，请在客户端/etc/hosts中设置其主机名对应IP解析')
    port = models.IntegerField(verbose_name='ssh端口', null=True, blank=True, default=22)
    other_ip = models.CharField(u"其它IP", max_length=100, null=True, blank=True)
    group = models.ForeignKey(HostGroup, verbose_name=u"组/安全区域", default=1, on_delete=models.SET_NULL, null=True, blank=True)
    # asset_no = models.CharField(u"资产编号", max_length=50, null=True, blank=True)
    # domain = models.CharField(u"安全区域", max_length=20, null=True, blank=True)
    status = models.SmallIntegerField(u"设备状态", choices=ASSET_STATUS, default=1, null=True, blank=True)
    asset_type = models.SmallIntegerField(u"设备类型", choices=ASSET_TYPE, default=1, null=True, blank=True)
    # 注意，django 1.11对postgresql 8.*低版本支持不好，ForeignKey字段有修改就会SQL报错 array_agg(attname ORDER BY rnum)
    machine = models.ForeignKey('self', verbose_name=u"所属物理机", limit_choices_to={'asset_type': 1},
                                on_delete=models.SET_NULL, null=True, blank=True, help_text='设备类型为虚拟机/容器时，设置所在物理机')
    os = models.CharField(u"操作系统", max_length=100, default='', null=True, blank=True)
    # vendor = models.CharField(u"设备厂商", max_length=50, null=True, blank=True)
    cpu_model = models.CharField(u"CPU型号", max_length=100, default='', null=True, blank=True)
    cpu_num = models.CharField(u"CPU数量", max_length=100, default='', null=True, blank=True, help_text='物理核个数, 逻辑核个数，(intel高端CPU带超线程技术)')
    memory = models.CharField(u"内存大小", max_length=30, default='', null=True, blank=True)
    disk = models.CharField(u"硬盘信息", max_length=255, default='', null=True, blank=True)
    vendor = models.CharField(u"供应商", max_length=150, default='', null=True, blank=True)
    sn = models.CharField(u"主机序列号", max_length=150, default='', null=True, blank=True)
    ports = models.TextField(u"监听端口", default='', null=True, blank=True, help_text='主机上处于监听状态的TCP和UDP端口')

    createtime = models.DateTimeField('创建时间',
                                      auto_now_add=True,
                                      # default=now,
                                      blank=True, null=True)
    changetime = models.DateTimeField('修改时间', auto_now=True, blank=True, null=True)
    agenttime = models.DateTimeField('配置更新', blank=True, null=True, help_text='最近一次主机客户端自动脚本运行更新软硬件信息的时间')

    usergroup = models.ManyToManyField(Group, verbose_name='网站用户组', blank=True, help_text='网站哪些用户组能对当前主机进行操作')
    user = models.ManyToManyField(User, verbose_name='网站用户权限', blank=True,
                                  # through='Host_User',  # 行级别的权限控制，人工录入时麻烦，比较困难实现快速批量设置主机清单
                                  help_text='网站哪些用户能对当前主机进行操作，超级用户直接有操作权限')
    ssh_user = models.ForeignKey(SshUser, verbose_name='SSH终端用户', on_delete=models.SET_NULL, null=True, blank=True, help_text='当前主机的SSH用户，用于ssh连接执行命令或终端WEB SSH')

    buydate = models.DateField('购买日期', default=datetime.today, blank=True, null=True)
    position = models.CharField(u"所处位置", max_length=250, default='', null=True, blank=True)
    sernumb = models.CharField(u"服务编号", max_length=150, default='', null=True, blank=True)
    sercode = models.CharField(u"服务代码", max_length=150, default='', null=True, blank=True)
    admin = models.ForeignKey(User, verbose_name='管理人', related_name='user_set2', null=True, blank=True, help_text='负责人直接有(当前主机/名下主机)操作权限')

    tomcat = models.CharField(max_length=100, verbose_name=u"Tomcat目录", default='/data/app/tomcat')
    tomcat_ver = models.CharField(max_length=50, verbose_name=u"Tomcat版本", default='', blank=True)
    jdk_ver = models.CharField(max_length=50, verbose_name=u"JDK版本", default='', blank=True)
    kernel = models.CharField(max_length=60, verbose_name=u"系统内核版本", default='', blank=True)

    # idc = models.ForeignKey(Idc, verbose_name=u"所在机房", on_delete=models.SET_NULL, null=True, blank=True)
    # position = models.CharField(u"所在位置", max_length=100, null=True, blank=True)
    # info = models.CharField(u"应用信息", max_length=200, default='', null=True, blank=True)
    text = models.TextField(u"备注信息", default='', null=True, blank=True)

    class Meta:
        permissions = (
            # 实现表级别的权限控制
            ("deploy_host", "Can deploy host"),    # APP部署
            ("ssh_host", "Can ssh host"),          # 终端登陆
            ("sftp_host", "Can sftp host"),        # 文件管理
            ("grep_host", "Can grep host"),        # 执行日志搜索
            ("run_sh_host", "Can run_sh host"),    # 执行常用命令
            ("run_cmd_host", "Can run_cmd host"),   # 执行自定义命令
            ("other_do_host", "Can other_do host"),  # 执行其它操作，如ES节点索引
        )
        ordering = ['group', 'ip']
        verbose_name = '主机'

    def __unicode__(self):
        return '%s - %s' % (self.name, self.ip)

    @staticmethod
    def newhost(kwargs):
        # 添加/修改host数据
        hostname = kwargs['hostname']
        host = Host.objects.filter(hostname=hostname)
        try:
            if host:
                host = host[0]
                # print '已有记录',hostname,'更新主机信息'
                kwargs.pop('hostname')
                text = kwargs.get('text', '')
                if text:
                    kwargs['text'] = '%s\r\n%s' % (host.text, text)  # 备注信息只在原基础信息上追加
                for k, v in kwargs.items():
                    setattr(host, k, v)
                host.agenttime = datetime.today()
                host.save()
            else:
                # 添加新主机
                hostname, ip = kwargs.get('hostname', ''), kwargs.get('ip', '')
                kwargs['name'] = kwargs.get('name', '%s' % (hostname, ))  # 当标识名未提供，则填入计算机名。
                kwargs['asset_type'] = kwargs.get('asset_type', 2)  # 默认为虚拟机类型
                kwargs['agenttime'] = datetime.today()  # 配制更新日期

                group_id = kwargs.get('group_id', HostGroup.get_group(ip))

                if group_id:
                    kwargs['group_id'] = group_id

                Host(**kwargs).save()
            return 1
        except:
            print(traceback.format_exc())
            return 0

    def get_ssh_user(self):
        # 获取某台主机SSH用户/密码

        ssh_user = self.ssh_user
        if not ssh_user:
            ssh_users = SshUser.objects.filter(username='app')  # 下面取id最小的app用户
            if ssh_users:
                ssh_user = ssh_users[0]
            else:
                print 'Error: SshUser数据表为空，新安装CMDB？'
                return '', ''
        username = ssh_user.username
        password = get_AES(password=ssh_user.password, encode=0)
        return username, password

    @staticmethod

cmdb/templates/docker/container.html
{% extends "_base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block  title %}容器管理{% endblock %}

{% block left %}
    {% include "_left.html" with cmdb_docker_container_active="active" %}
{% endblock left %}


{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:docker_host_list' %}">Docker管理</a>
                </li>
                <li class="active">
                    <strong>容器管理 - {{ client.dockerhost }}</strong>{% if netype %} - 网络类型({{ netype }}){% endif %}
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row wrapper wrapper-content animated fadeInRight">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="col-md-8 form-inline">
                        <label class="text-success">宿主机:</label>
                        
                        <select id="dockerhost" class="form-control">
                            {% if not client %}<option value="">------</option>{% endif %}
                            {% for row in dockerhosts %}
                            <option value="{{ row.id }}" {% if row == client.dockerhost %}selected{% endif %}>{{ row }}</option>
                            {% endfor %}
                        </select>

                    </div>


                </div>
                <div class="ibox-content">
                    {% if error %}
                    {{ error }}
                    {% elif client %}
                    <a href="{% url 'cmdb:docker_container_add' client.dockerhost.id %}" class="btn btn-primary"> 添加</a>
                    <a class="btn btn-danger" id="delall">批量删除</a>

                    <table class="table table-striped table-bordered table-hover dataTables-example" id="tb">
                        <thead>
                            <tr>
                                <th><input type="checkbox" id="CheckedAll"></th>
                                <th class="col-xs-4">名称</th>
                                <th class="col-xs-2">镜像</th>
                                <th class="col-xs-1">容器IP</th>
                                <th class="col-xs-1">状态</th>
                                <th class="col-lg-1">创建</th>
                                <th class="col-xs-3">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in cons %}
                            <tr>
                                <td><input type="checkbox" value="{{ i.id }}"  name="id"></td>
                                <td>{{ i.name }}</td>
                                <td>{{ i.image }}</td>
                                <td>{{ i.ip }}</td>
                                <td>{{ i.status }}</td>
                                <td>{{ i.time }}</td>
                                {# <td>{{ i.runtime }}</td> #}

                                <td>
                                    <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal">详情</button>
                                    <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#myModal">日志</button>
                                    <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal">启动</button>
                                    <button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#myModal">停止</button>
                                    <a class="btn btn-success btn-xs btn-outline" href="{% url 'cmdb:docker_webssh' %}?host={{ client.dockerhost.id }}&container={{ i.name }}" target="_blank">终端</a>
                                    <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal">删除</button>
                                </td>
                            </tr>
                            {% endfor %}


                        </tbody>

                    </table>
                    {% else %}
                    请选择宿主机/物理机
                    {% endif %}

                </div>
            </div>
        </div>


    </div>


    <!-- 操作返回 - 模态框（Modal） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="false">
                        &times;
                    </button>
                    <span id="server"></span>
                </div>
                <div class="modal-body">
                    <textarea id="server_msg" readonly style="width:100%;" rows="5">{{ text }}</textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                    </button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block footer-js %}
    <script>
        function conn_docker(url, textarea_height){
            $.ajax({
                url: url,
                type: 'GET',
                timeout: 20000,
                error: function(){
                    $("#server_msg").html('<option value="">网站连接失败！请联系CMDB管理员</option>');
                },
                success: function(msg_html){
                    // json格式化
                    // console.log(msg_html);
                    try{
                        var msg = JSON.parse(msg_html);
                        console.log(msg.remove);
                        if (msg.remove=="ok") {
                            // 删除成功，刷新页面
                            location.reload()
                        }
                        var msg_html = JSON.stringify(msg, null, 4);
                    }catch(err){}finally{
                        $('#server_msg').val(msg_html);
                        // console.log(txt);
                        $('#server_msg')[0].style.minHeight= textarea_height;
                    } 
                }
            });
        };

        $(document).ready(function(){

            $('#dockerhost').change(function() {
                // 宿主机下拉框选择后
                if (this.value) {
                    console.log(this.value);
                    window.location.href="{% url 'cmdb:docker_container' %}"+this.value+"/"
                }
            });

            {% if client %}

            // $( ".btn-danger.btn-xs" ).click()
            $('#tb').on('click', 'button', function (e) {
                // console.log($(this));
                var url="{% url 'cmdb:docker_container_do' client.dockerhost.id %}?id="+this.parentElement.parentElement.children[0].children[0].value;
                var textarea_height="400px";
                if (this.className=="btn btn-danger btn-xs") {
                    if(! window.confirm('确认删除容器？')){
                        return false;
                    }
                    var url="{% url 'cmdb:docker_container_rm' client.dockerhost.id %}?id="+this.parentElement.parentElement.children[0].children[0].value;
                    textarea_height="100px";
                } else if (this.className=="btn btn-primary btn-xs") {
                    url=url+"&do=start";
                    textarea_height="100px";
                } else if (this.className=="btn btn-success btn-xs btn-outline") {
                    // 终端、命令
                    url=url+"&do=exec_run";
                    // return false;
                } else if (this.className=="btn btn-success btn-xs") {
                    url=url+"&do=logs";
                } else if (this.className=="btn btn-info btn-xs") {
                    url=url+"&do=attrs";
                } else if (this.className=="btn btn-warning btn-xs") {
                    url=url+"&do=stop";
                    textarea_height="100px";
                }

                $("#server_div").show();
                $("#server").text(this.parentElement.parentElement.children[1].textContent+" "+this.textContent);
                // console.log(url);
                conn_docker(url, textarea_height);

            });


            $("#delall").click(function(){
                var container_ids = '';
                var cs=document.getElementsByName('id');
                for (i=0; i < cs.length; i++) {
                    if (cs[i].checked) {
                        container_ids = container_ids+cs[i].value+',';
                        // console.log(cs[i].value);
                    }
                }
                if (! container_ids) {return false;}
                if(! window.confirm('确认批量删除容器？')){
                    return false;
                }
                var url="{% url 'cmdb:docker_container_rm' client.dockerhost.id %}?id="+container_ids;
                console.log(container_ids);
                $("#server_div").show();
                $("#server").text("批量删除容器");
                conn_docker(url, "100px");
            });
            {% endif %}

        });


    </script>
{% endblock footer-js %}



cmdb/templates/docker/yml_list.html
{% extends "_base.html" %}


{% block  title %}容器YML列表{% endblock %}

{% block left %}
    {% include "_left.html" with cmdb_docker_yml_active="active" %}
{% endblock left %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>容器管理</a>
                </li>
                <li class="active">
                    <strong>容器YML列表</strong>
                </li>
            </ol>
        </div>

    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Docker-Compose yml列表</h5>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <a href="{% url 'cmdb:docker_yml_add' %}" class="btn btn-primary">新建YML</a>
                            <a href="/admin/cmdb/dockerymlgroup/" class="btn btn-info" target="_blank">组类管理</a>

                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>标识</th>
                                    <th>组类</th>
                                    <th>文件名</th>
                                    <th>状态</th>
                                    <th class="col-lg-3">动作</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for row in object_list %}

                                    <tr>
                                        <td class="center">
                                            <a href="{% url 'cmdb:docker_yml_edit' row.id %}">{{ row.name }}</a>
                                        </td>
                                        <td class="center">{{ row.group }}</td>
                                        <td class="center">{{ row.file }}</td>
                                        <td><i class="fa fa-{% if row.state %}check-square text-navy{% else %}minus-square text-danger{% endif %}"></i></td>
                                        <td>
                                            <a class="btn btn-success btn-xs" href="{% url 'cmdb:docker_compose_list' %}?yml={{ row.id }}">容器编排</a>
                                            <a class="btn btn-primary  btn-xs " href="/admin/cmdb/dockeryml/{{ row.id }}/change/" target="_blank">编辑</a>
                                            {# <button type="button" class="btn btn-danger btn-xs">删除</button> #}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>

                            </table>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock page-content %}
